<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-QM8BET5" failures="0" tests="3" name="Hapana.Tests.ErrorValidations" time="36.131" errors="1" timestamp="19 Jul 2023 11:06:35 GMT" skipped="1">
  <testcase classname="Hapana.Tests.ErrorValidations" name="ProductErrorValidation" time="13.451">
    <skipped/>
  </testcase> <!-- ProductErrorValidation -->
  <testcase classname="Hapana.Tests.ErrorValidations" name="loginErrorValidation" time="5.714"/>
  <testcase classname="Hapana.Tests.ErrorValidations" name="ProductErrorValidation" time="16.966">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at Hapana.PageObjects.productcatalauge.addproductToCart(productcatalauge.java:55)
at Hapana.Tests.ErrorValidations.ProductErrorValidation(ErrorValidations.java:30)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
    </error>
  </testcase> <!-- ProductErrorValidation -->
</testsuite> <!-- Hapana.Tests.ErrorValidations -->
